### PR TITLE
refactor: change host function API and hide GuestRuntime

### PR DESCRIPTION
**Pull request by mhmd-azeez**
I wanted to change these before hitting 1.0 for the go-sdk:
- I think we should hide HostFunction creation behind a function so that we have flexibility of adding new function callbacks in the future
- And I think GuestRuntime is an implementation detail and doesn't need to be public

### CODE REVIEW

**Comment by mhmd-azeez** [comment]
@zshipko @bhelx @nilslice will merge this PR if no one has any objections

**Comment by nilslice** [comment]
I think this looks great -- will wait for one other review though.. someone a little closer to the previous Host Functions impl would be ideal!

**Comment by mhmd-azeez** [comment]
cc @k33g you might need to update your demo for your talk

**Comment by k33g** [comment]
@mhmd-azeez thanks for the notification, I will have a look :)

**Pull request merged**
